#!/usr/bin/env python3

# BMI = (weight in kg / height in metere sqrd)
# Imperial version: BMI * 703


def gather_info():
    h = float(input("What is your height? (inches or or meters) "))
    w = float(input("What is your weight? (pounds or meters) "))
    system = input("metric or imperial? ").lower().strip()

    return (h, w, system)


def calc_bmi(w, h, system='meteric'):
    """
    Return the body mass index (BMI) for the
    given weight, height, and measurement system.
    """

    if system == 'metric':
        bmi = (w/h**2)
    else:
        bmi = 703 * (w/h**2)

    return bmi


while True:
    height, weight, system = gather_info()
    if system.startswith('i'):
        bmi = calc_bmi(weight, height, system)
        print(f"Your BMI is {bmi}")
        break
    elif system.startswith('m'):
        bmi = calc_bmi(weight, height)
        print(f"Your BMI is {bmi}")
        break
    else:
        print("Error: Unknonw measurement system: Please use imperial or metric?")