#!/usr/bin/env python3

import time
from time import localtime, mktime, strftime

start_time = localtime()
print(f"Timer started: {strftime('%X', start_time)}")

# Wait for user to stop timer
input("Press 'Enter' to stop timer ")

stop_time = localtime()
diff = mktime(stop_time) - mktime(start_time)


print(f"Timer stopped at: {strftime('%X', stop_time)}")
print(f"Total time: {diff} seconds")
